-- Esquema compartido de MINEX.
-- Ejecutar una vez en Supabase > SQL Editor con un usuario administrador.

-- Permisos de datos operativos para usuarios autenticados.
-- Son necesarios para editar y eliminar desde Configuración.
do $$
begin
  execute 'drop policy if exists "Authenticated users can read cases" on public.cases';
  execute 'drop policy if exists "Authenticated users can insert cases" on public.cases';
  execute 'drop policy if exists "Authenticated users can update cases" on public.cases';
  execute 'drop policy if exists "Authenticated users can delete cases" on public.cases';
  execute 'create policy "Authenticated users can read cases" on public.cases for select to authenticated using (true)';
  execute 'create policy "Authenticated users can insert cases" on public.cases for insert to authenticated with check (true)';
  execute 'create policy "Authenticated users can update cases" on public.cases for update to authenticated using (true) with check (true)';
  execute 'create policy "Authenticated users can delete cases" on public.cases for delete to authenticated using (true)';
  execute 'drop policy if exists "Authenticated users can read employees" on public.employees';
  execute 'drop policy if exists "Authenticated users can insert employees" on public.employees';
  execute 'drop policy if exists "Authenticated users can update employees" on public.employees';
  execute 'drop policy if exists "Authenticated users can delete employees" on public.employees';
  execute 'create policy "Authenticated users can read employees" on public.employees for select to authenticated using (true)';
  execute 'create policy "Authenticated users can insert employees" on public.employees for insert to authenticated with check (true)';
  execute 'create policy "Authenticated users can update employees" on public.employees for update to authenticated using (true) with check (true)';
  execute 'create policy "Authenticated users can delete employees" on public.employees for delete to authenticated using (true)';
exception
  when undefined_table then
    raise notice 'Las tablas cases o employees aún no existen; cree las tablas antes de aplicar sus políticas.';
end $$;

create table if not exists public.duplicate_reviews (
  id bigint generated by default as identity primary key,
  item text,
  data jsonb not null default '{}'::jsonb,
  review_status text not null default 'PENDIENTE',
  detected_at date,
  detected_by text,
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.duplicate_reviews enable row level security;

drop policy if exists "Authenticated users can read duplicate reviews" on public.duplicate_reviews;
create policy "Authenticated users can read duplicate reviews"
  on public.duplicate_reviews for select to authenticated using (true);

drop policy if exists "Authenticated users can insert duplicate reviews" on public.duplicate_reviews;
create policy "Authenticated users can insert duplicate reviews"
  on public.duplicate_reviews for insert to authenticated with check (true);

drop policy if exists "Authenticated users can update duplicate reviews" on public.duplicate_reviews;
create policy "Authenticated users can update duplicate reviews"
  on public.duplicate_reviews for update to authenticated using (true) with check (true);

drop policy if exists "Authenticated users can delete duplicate reviews" on public.duplicate_reviews;
create policy "Authenticated users can delete duplicate reviews"
  on public.duplicate_reviews for delete to authenticated using (true);

do $$
begin
  alter publication supabase_realtime add table public.duplicate_reviews;
exception
  when duplicate_object then null;
end $$;
