-- Esquema compartido de MINEX.
-- Ejecutar una vez en Supabase > SQL Editor con un usuario administrador.

create table if not exists public.duplicate_reviews (
  id bigint generated by default as identity primary key,
  item text,
  data jsonb not null default '{}'::jsonb,
  review_status text not null default 'PENDIENTE',
  detected_at date,
  detected_by text,
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.duplicate_reviews enable row level security;

drop policy if exists "Authenticated users can read duplicate reviews" on public.duplicate_reviews;
create policy "Authenticated users can read duplicate reviews"
  on public.duplicate_reviews for select to authenticated using (true);

drop policy if exists "Authenticated users can insert duplicate reviews" on public.duplicate_reviews;
create policy "Authenticated users can insert duplicate reviews"
  on public.duplicate_reviews for insert to authenticated with check (true);

drop policy if exists "Authenticated users can update duplicate reviews" on public.duplicate_reviews;
create policy "Authenticated users can update duplicate reviews"
  on public.duplicate_reviews for update to authenticated using (true) with check (true);

drop policy if exists "Authenticated users can delete duplicate reviews" on public.duplicate_reviews;
create policy "Authenticated users can delete duplicate reviews"
  on public.duplicate_reviews for delete to authenticated using (true);

do $$
begin
  alter publication supabase_realtime add table public.duplicate_reviews;
exception
  when duplicate_object then null;
end $$;
